-- Create a table for public profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  role text default 'patient'::text,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Create a function to handle new user signups and automatically create a profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Create a table for therapists
create table if not exists public.therapists (
  id bigint generated by default as identity primary key,
  name text not null,
  specialty text,
  rating numeric(3,1) default 0.0,
  reviews_count integer default 0,
  experience text,
  fee numeric(10,2),
  image_url text,
  available boolean default true,
  system_prompt text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for therapists
alter table public.therapists enable row level security;

-- Therapists are viewable by everyone
create policy "Therapists are viewable by everyone." on public.therapists
  for select using (true);

-- (Only admins would be able to insert/update therapists, we can leave this restricted for now)


-- Create a table for bookings (currently using localStorage, but good to have ready)
create table if not exists public.bookings (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade,
  therapist_id bigint references public.therapists on delete cascade,
  booking_date date not null,
  booking_time time not null,
  status text default 'scheduled'::text check (status in ('scheduled', 'completed', 'cancelled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for bookings
alter table public.bookings enable row level security;

-- Users can view their own bookings
create policy "Users can view own bookings." on public.bookings
  for select using (auth.uid() = user_id);

-- Users can insert their own bookings
create policy "Users can insert own bookings." on public.bookings
  for insert with check (auth.uid() = user_id);

-- Users can update their own bookings
create policy "Users can update own bookings." on public.bookings
  for update using (auth.uid() = user_id);


-- Insert original 6 therapists
insert into public.therapists (name, specialty, rating, reviews_count, experience, fee, image_url, available, system_prompt)
values 
  ('Dr. Sarah Johnson', 'Pediatric Speech Therapy', 4.9, 127, '12 years', 80.00, 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop&crop=face', true, 'You are Dr. Sarah Johnson, an empathetic pediatric speech therapist...'),
  ('Dr. Michael Chen', 'Fluency & Stuttering', 4.8, 98, '8 years', 75.00, 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop&crop=face', true, 'You are Dr. Michael Chen, a specialist in stuttering and fluency disorders...'),
  ('Dr. Emily Roberts', 'Voice Disorders', 4.9, 156, '15 years', 90.00, 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop&crop=face', false, 'You are Dr. Emily Roberts, a speech therapist specializing in voice disorders...'),
  ('Dr. James Wilson', 'Articulation Therapy', 4.7, 84, '6 years', 70.00, 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop&crop=face', true, 'You are Dr. James Wilson, specializing in articulation therapy...'),
  ('Dr. Lisa Martinez', 'Cognitive-Communication', 4.8, 112, '10 years', 85.00, 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=200&h=200&fit=crop&crop=face', true, 'You are Dr. Lisa Martinez, an expert in cognitive-communication therapy...'),
  ('Dr. David Kim', 'Swallowing Disorders', 4.6, 67, '5 years', 65.00, 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop&crop=face', false, 'You are Dr. David Kim, an SLP specializing in swallowing disorders...');

-- Create a table for practice sessions
create table if not exists public.practice_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade,
  accuracy numeric(5,2),
  phrase text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for practice sessions
alter table public.practice_sessions enable row level security;

-- Users can view and insert their own practice sessions
create policy "Users can view own practice sessions." on public.practice_sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert own practice sessions." on public.practice_sessions
  for insert with check (auth.uid() = user_id);

-- Create a table for game sessions
create table if not exists public.game_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade,
  game_id integer not null,
  score numeric(5,2),
  duration_seconds integer,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for game sessions
alter table public.game_sessions enable row level security;

-- Users can view and insert their own game sessions
create policy "Users can view own game sessions." on public.game_sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert own game sessions." on public.game_sessions
  for insert with check (auth.uid() = user_id);

-- Create a table for chat messages
create table if not exists public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade,
  therapist_id integer not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for chat messages
alter table public.chat_messages enable row level security;

-- Users can view and insert their own chat messages
create policy "Users can view own chat messages." on public.chat_messages
  for select using (auth.uid() = user_id);

create policy "Users can insert own chat messages." on public.chat_messages
  for insert with check (auth.uid() = user_id);

-- Create a table for therapist memories (summaries of conversations)
create table if not exists public.therapist_memories (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade,
  therapist_id integer not null,
  summary text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, therapist_id)
);

-- Enable RLS for therapist memories
alter table public.therapist_memories enable row level security;

-- Users can view and update their own therapist memories
create policy "Users can view own therapist memories." on public.therapist_memories
  for select using (auth.uid() = user_id);

create policy "Users can insert own therapist memories." on public.therapist_memories
  for insert with check (auth.uid() = user_id);

create policy "Users can update own therapist memories." on public.therapist_memories
  for update using (auth.uid() = user_id);

